var JSON_kepzettsegek = [
{"id":0, "name":"Fegyverhasználat", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":[]},
{"id":1, "name":"Fájdalomtűrés", "category":"H", "type":"N", "spec":0, "nehez":2, "tul":["all","aka"]},
{"id":2, "name":"Fegyverhasználat – Tőr jellegű fegyverek", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["gyo","ugy"]},
{"id":3, "name":"Fegyverhasználat – Botok", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["ero","gyo","ugy"]},
{"id":4, "name":"Fegyverhasználat – Buzogányok", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["ero","ugy"]},
{"id":5, "name":"Fegyverhasználat – Egykezes kardok", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["ero","gyo","ugy"]},
{"id":6, "name":"Fegyverhasználat – Csatabárdok", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["ero","ugy"]},
{"id":7, "name":"Fegyverhasználat – Nehéz kardok", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["ero","ugy"]},
{"id":8, "name":"Fegyverhasználat – Nyeles fegyverek", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["ero","ugy"]},
{"id":9, "name":"Fegyverhasználat – Hajítófegyverek", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["ugy","erz"]},
{"id":10, "name":"Fegyverhasználat – Íjak", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["ugy","erz"]},
{"id":11, "name":"Fegyverhasználat – Nyílpuskák", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["ugy","erz"]},
{"id":12, "name":"Fegyverhasználat – Egyéb", "category":"H", "type":"N", "spec":1, "nehez":3, "tul":["ugy","erz"]},
{"id":13, "name":"Fegyverismeret", "category":"H", "type":"N", "spec":0, "nehez":2, "tul":["int","erz"]},
{"id":14, "name":"Hadvezetés", "category":"H", "type":"N", "spec":0, "nehez":3, "tul":["int","kar"]},
{"id":15, "name":"Harci láz", "category":"H", "type":"N", "spec":0, "nehez":2, "tul":["all","ege"]},
{"id":16, "name":"Harcművészet", "category":"H", "type":"N", "spec":1, "nehez":4, "tul":["ero","gyo","ugy","aka"]},
{"id":17, "name":"Harctéri gyakorlat", "category":"H", "type":"N", "spec":0, "nehez":2, "tul":["gyo","ugy","erz"]},
{"id":18, "name":"Kétkezesharc", "category":"H", "type":"N", "spec":0, "nehez":3, "tul":["gyo","ugy"]},
{"id":19, "name":"Pajzshasználat", "category":"H", "type":"N", "spec":0, "nehez":2, "tul":["ero","ugy"]},
{"id":20, "name":"Pusztakezes harc", "category":"H", "type":"N", "spec":0, "nehez":2, "tul":["ero","ugy","all"]},
{"id":21, "name":"Pusztítás", "category":"H", "type":"N", "spec":0, "nehez":2, "tul":["ero"]},
{"id":22, "name":"Taktika", "category":"H", "type":"N", "spec":0, "nehez":2, "tul":["erz"]},
{"id":23, "name":"Vakharc", "category":"H", "type":"N", "spec":0, "nehez":3, "tul":["erz"]},
{"id":24, "name":"Vértviselet", "category":"H", "type":"N", "spec":0, "nehez":2, "tul":["ero"]},
{"id":25, "name":"Álcázás/álruha", "category":"A", "type":"N", "spec":0, "nehez":2, "tul":["ugy","erz"]},
{"id":26, "name":"Hamisítás", "category":"A", "type":"N", "spec":0, "nehez":3, "tul":["ugy","int"]},
{"id":27, "name":"Jelbeszéd", "category":"A", "type":"N", "spec":0, "nehez":2, "tul":["erz","int"]},
{"id":28, "name":"Kocsmai verekedés", "category":"A", "type":"N", "spec":0, "nehez":1, "tul":["ero","gyo","ugy"]},
{"id":29, "name":"Méregkeverés", "category":"A", "type":"N", "spec":0, "nehez":2, "tul":["int"]},
{"id":30, "name":"Orvtámadás", "category":"A", "type":"N", "spec":0, "nehez":2, "tul":["ugy"]},
{"id":31, "name":"Kínzás", "category":"A", "type":"N", "spec":0, "nehez":2, "tul":["ugy","int"]},
{"id":32, "name":"Szabadulóművészet", "category":"A", "type":"N", "spec":0, "nehez":3, "tul":["ugy"]},
{"id":33, "name":"Szerencsejáték", "category":"A", "type":"N", "spec":1, "nehez":2, "tul":["ugy","int"]},
{"id":34, "name":"Csapdakeresés", "category":"A", "type":"S", "spec":0, "nehez":0, "tul":[]},
{"id":35, "name":"Lopódzás", "category":"A", "type":"S", "spec":0, "nehez":0, "tul":[]},
{"id":36, "name":"Rejtőzködés", "category":"A", "type":"S", "spec":0, "nehez":0, "tul":[]},
{"id":37, "name":"Rejtekhely kutatás", "category":"A", "type":"S", "spec":0, "nehez":0, "tul":[]},
{"id":38, "name":"Zárnyitás", "category":"A", "type":"S", "spec":0, "nehez":0, "tul":[]},
{"id":39, "name":"Zsebmetszés", "category":"A", "type":"S", "spec":0, "nehez":0, "tul":[]},
{"id":40, "name":"Veszélyérzék", "category":"A", "type":"S", "spec":0, "nehez":0, "tul":[]},
{"id":41, "name":"Állatismeret", "category":"V", "type":"N", "spec":1, "nehez":1, "tul":[]},
{"id":42, "name":"Csapdaállítás", "category":"V", "type":"N", "spec":0, "nehez":2, "tul":["ugy"]},
{"id":43, "name":"Csomózás", "category":"V", "type":"N", "spec":0, "nehez":2, "tul":["ugy"]},
{"id":44, "name":"Értékbecslés", "category":"V", "type":"N", "spec":0, "nehez":1, "tul":["int","erz"]},
{"id":45, "name":"Futás", "category":"V", "type":"N", "spec":0, "nehez":1, "tul":["all","ege"]},
{"id":46, "name":"Hajózás", "category":"V", "type":"N", "spec":0, "nehez":2, "tul":[]},
{"id":47, "name":"Hangutánzás", "category":"V", "type":"N", "spec":0, "nehez":2, "tul":["erz"]},
{"id":48, "name":"Helyismeret", "category":"V", "type":"N", "spec":1, "nehez":1, "tul":[]},
{"id":49, "name":"Idomítás", "category":"V", "type":"N", "spec":1, "nehez":2, "tul":["asz"]},
{"id":50, "name":"Időjóslás", "category":"V", "type":"N", "spec":0, "nehez":2, "tul":["erz","int"]},
{"id":51, "name":"Kocsihajtás", "category":"V", "type":"N", "spec":0, "nehez":1, "tul":["ugy"]},
{"id":52, "name":"Lovaglás", "category":"V", "type":"N", "spec":0, "nehez":1, "tul":["ugy"]},
{"id":53, "name":"Nyomolvasás", "category":"V", "type":"N", "spec":0, "nehez":2, "tul":["erz"]},
{"id":54, "name":"Szakma", "category":"V", "type":"N", "spec":1, "nehez":2, "tul":[]},
{"id":55, "name":"Úszás", "category":"V", "type":"N", "spec":0, "nehez":1, "tul":["ero","all","ege"]},
{"id":56, "name":"Vadonjárás", "category":"V", "type":"N", "spec":0, "nehez":2, "tul":["erz"]},
{"id":57, "name":"Akrobatika", "category":"V", "type":"S", "spec":0, "nehez":0, "tul":[]},
{"id":58, "name":"Esés", "category":"V", "type":"S", "spec":0, "nehez":0, "tul":[]},
{"id":59, "name":"Mászás", "category":"V", "type":"S", "spec":0, "nehez":0, "tul":[]},
{"id":60, "name":"Alkímia", "category":"T", "type":"N", "spec":0, "nehez":3, "tul":["int"]},
{"id":61, "name":"Élettan", "category":"T", "type":"N", "spec":0, "nehez":3, "tul":["int"]},
{"id":62, "name":"Építészet", "category":"T", "type":"N", "spec":0, "nehez":3, "tul":["int"]},
{"id":63, "name":"Herbalizmus", "category":"T", "type":"N", "spec":0, "nehez":2, "tul":["int"]},
{"id":64, "name":"Írás/Olvasás", "category":"T", "type":"N", "spec":0, "nehez":3, "tul":["int"]},
{"id":65, "name":"Jog/Törvénykezés", "category":"T", "type":"N", "spec":0, "nehez":3, "tul":["int","asz"]},
{"id":66, "name":"Legendaismeret", "category":"T", "type":"N", "spec":0, "nehez":2, "tul":["int"]},
{"id":67, "name":"Mechanika", "category":"T", "type":"N", "spec":0, "nehez":3, "tul":["int","ugy"]},
{"id":68, "name":"Oktatás", "category":"T", "type":"N", "spec":0, "nehez":3, "tul":["int","asz"]},
{"id":69, "name":"Orvoslás", "category":"T", "type":"N", "spec":0, "nehez":3, "tul":["int"]},
{"id":70, "name":"Ősi nyelv", "category":"T", "type":"N", "spec":1, "nehez":4, "tul":["int"]},
{"id":71, "name":"Számtan/Mértan", "category":"T", "type":"N", "spec":0, "nehez":3, "tul":["int"]},
{"id":72, "name":"Térképészet", "category":"T", "type":"N", "spec":0, "nehez":3, "tul":["int"]},
{"id":73, "name":"Történelem", "category":"T", "type":"N", "spec":0, "nehez":2, "tul":["int"]},
{"id":74, "name":"Vallásismeret", "category":"T", "type":"N", "spec":0, "nehez":2, "tul":["int","asz"]},
{"id":75, "name":"Ékesszólás", "category":"S", "type":"N", "spec":0, "nehez":2, "tul":["int","asz","kar"]},
{"id":76, "name":"Heraldika", "category":"S", "type":"N", "spec":0, "nehez":2, "tul":["int"]},
{"id":77, "name":"Kultúra", "category":"S", "type":"N", "spec":1, "nehez":1, "tul":[]},
{"id":78, "name":"Lélektan", "category":"S", "type":"N", "spec":0, "nehez":3, "tul":["int","asz","erz"]},
{"id":79, "name":"Művészetek", "category":"S", "type":"N", "spec":1, "nehez":2, "tul":[]},
{"id":80, "name":"Nyelvtudás", "category":"S", "type":"N", "spec":1, "nehez":1, "tul":[]},
{"id":81, "name":"Párbaj", "category":"S", "type":"N", "spec":0, "nehez":2, "tul":["int","asz","kar"]},
{"id":82, "name":"Politika/diplomácia", "category":"S", "type":"N", "spec":0, "nehez":3, "tul":["asz","kar","int"]},
{"id":83, "name":"Szexuális kultúra", "category":"S", "type":"N", "spec":0, "nehez":1, "tul":["asz","kar"]},
{"id":84, "name":"Színészet", "category":"S", "type":"N", "spec":0, "nehez":3, "tul":["asz","kar"]},
{"id":85, "name":"Udvari etikett/intrika", "category":"S", "type":"N", "spec":0, "nehez":2, "tul":["int","asz","kar"]},
{"id":86, "name":"Démonológia", "category":"M", "type":"N", "spec":0, "nehez":4, "tul":["int","aka"]},
{"id":87, "name":"Drágakőmágia", "category":"M", "type":"N", "spec":0, "nehez":4, "tul":["int","aka","asz"]},
{"id":88, "name":"Magasmágia", "category":"M", "type":"N", "spec":1, "nehez":4, "tul":["int","aka","asz"]},
{"id":89, "name":"Nekromancia", "category":"M", "type":"N", "spec":0, "nehez":4, "tul":["int","aka","asz"]},
{"id":90, "name":"Őselemi mágia", "category":"M", "type":"N", "spec":0, "nehez":4, "tul":["int","aka","asz"]},
{"id":91, "name":"Pszi", "category":"M", "type":"N", "spec":1, "nehez":4, "tul":["int","aka","asz"]},
{"id":92, "name":"Rúnamágia", "category":"M", "type":"N", "spec":0, "nehez":4, "tul":["int","aka","asz"]},
{"id":93, "name":"Tapasztalati mágia", "category":"M", "type":"N", "spec":1, "nehez":4, "tul":["int","aka","asz"]}
]